/*
 * Roaming REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Transaction remote start request by EMP
 */
@ApiModel(description = "Transaction remote start request by EMP")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T18:37:18.317+01:00")
public class AuthorizeRemoteStartDTO {
  @SerializedName("evseId")
  private String evseId = null;

  @SerializedName("idTag")
  private String idTag = null;

  @SerializedName("externalSessionId")
  private String externalSessionId = null;

  @SerializedName("empSessionId")
  private String empSessionId = null;

  public AuthorizeRemoteStartDTO evseId(String evseId) {
    this.evseId = evseId;
    return this;
  }

   /**
   * Get evseId
   * @return evseId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getEvseId() {
    return evseId;
  }

  public void setEvseId(String evseId) {
    this.evseId = evseId;
  }

  public AuthorizeRemoteStartDTO idTag(String idTag) {
    this.idTag = idTag;
    return this;
  }

   /**
   * Get idTag
   * @return idTag
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIdTag() {
    return idTag;
  }

  public void setIdTag(String idTag) {
    this.idTag = idTag;
  }

  public AuthorizeRemoteStartDTO externalSessionId(String externalSessionId) {
    this.externalSessionId = externalSessionId;
    return this;
  }

   /**
   * Get externalSessionId
   * @return externalSessionId
  **/
  @ApiModelProperty(value = "")
  public String getExternalSessionId() {
    return externalSessionId;
  }

  public void setExternalSessionId(String externalSessionId) {
    this.externalSessionId = externalSessionId;
  }

  public AuthorizeRemoteStartDTO empSessionId(String empSessionId) {
    this.empSessionId = empSessionId;
    return this;
  }

   /**
   * Optional session id from EMP System, internal only. For UI requests, the backend will generated the ID.
   * @return empSessionId
  **/
  @ApiModelProperty(value = "Optional session id from EMP System, internal only. For UI requests, the backend will generated the ID.")
  public String getEmpSessionId() {
    return empSessionId;
  }

  public void setEmpSessionId(String empSessionId) {
    this.empSessionId = empSessionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizeRemoteStartDTO authorizeRemoteStartDTO = (AuthorizeRemoteStartDTO) o;
    return Objects.equals(this.evseId, authorizeRemoteStartDTO.evseId) &&
        Objects.equals(this.idTag, authorizeRemoteStartDTO.idTag) &&
        Objects.equals(this.externalSessionId, authorizeRemoteStartDTO.externalSessionId) &&
        Objects.equals(this.empSessionId, authorizeRemoteStartDTO.empSessionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(evseId, idTag, externalSessionId, empSessionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizeRemoteStartDTO {\n");
    
    sb.append("    evseId: ").append(toIndentedString(evseId)).append("\n");
    sb.append("    idTag: ").append(toIndentedString(idTag)).append("\n");
    sb.append("    externalSessionId: ").append(toIndentedString(externalSessionId)).append("\n");
    sb.append("    empSessionId: ").append(toIndentedString(empSessionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

