/*
 * CS Management CSO REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.VersionedData;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ChargingStationStatusDataDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T19:08:37.674+01:00")
public class ChargingStationStatusDataDTO {
  @SerializedName("versionedData")
  private VersionedData versionedData = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    AVAILABLE("AVAILABLE"),
    
    PREPARING("PREPARING"),
    
    CHARGING("CHARGING"),
    
    SUSPENDED_EVSE("SUSPENDED_EVSE"),
    
    SUSPENDED_EV("SUSPENDED_EV"),
    
    FINISHING("FINISHING"),
    
    OCCUPIED("OCCUPIED"),
    
    RESERVED("RESERVED"),
    
    UNAVAILABLE("UNAVAILABLE"),
    
    FAULTED("FAULTED"),
    
    OFFLINE("OFFLINE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  /**
   * Gets or Sets errorCode
   */
  @JsonAdapter(ErrorCodeEnum.Adapter.class)
  public enum ErrorCodeEnum {
    CONNECTOR_LOCK_FAILURE("CONNECTOR_LOCK_FAILURE"),
    
    EV_COMMUNICATION_ERROR("EV_COMMUNICATION_ERROR"),
    
    GROUND_FAILURE("GROUND_FAILURE"),
    
    HIGH_TEMPERATURE("HIGH_TEMPERATURE"),
    
    INTERNAL_ERROR("INTERNAL_ERROR"),
    
    LOCAL_LIST_CONFLICT("LOCAL_LIST_CONFLICT"),
    
    NO_ERROR("NO_ERROR"),
    
    OTHER_ERROR("OTHER_ERROR"),
    
    OVER_CURRENT_FAILURE("OVER_CURRENT_FAILURE"),
    
    POWER_METER_FAILURE("POWER_METER_FAILURE"),
    
    POWER_SWITCH_FAILURE("POWER_SWITCH_FAILURE"),
    
    READER_FAILURE("READER_FAILURE"),
    
    RESET_FAILURE("RESET_FAILURE"),
    
    UNDER_VOLTAGE("UNDER_VOLTAGE"),
    
    OVER_VOLTAGE("OVER_VOLTAGE"),
    
    WEAK_SIGNAL("WEAK_SIGNAL");

    private String value;

    ErrorCodeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ErrorCodeEnum fromValue(String text) {
      for (ErrorCodeEnum b : ErrorCodeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ErrorCodeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ErrorCodeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ErrorCodeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ErrorCodeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("errorCode")
  private ErrorCodeEnum errorCode = null;

  @SerializedName("info")
  private String info = null;

  @SerializedName("lastStatusNotificationTimestamp")
  private OffsetDateTime lastStatusNotificationTimestamp = null;

  @SerializedName("lastStatusNotificationReceived")
  private OffsetDateTime lastStatusNotificationReceived = null;

  @SerializedName("statusVendorId")
  private String statusVendorId = null;

  @SerializedName("vendorErrorCode")
  private String vendorErrorCode = null;

  public ChargingStationStatusDataDTO versionedData(VersionedData versionedData) {
    this.versionedData = versionedData;
    return this;
  }

   /**
   * Get versionedData
   * @return versionedData
  **/
  @ApiModelProperty(value = "")
  public VersionedData getVersionedData() {
    return versionedData;
  }

  public void setVersionedData(VersionedData versionedData) {
    this.versionedData = versionedData;
  }

  public ChargingStationStatusDataDTO status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ChargingStationStatusDataDTO errorCode(ErrorCodeEnum errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(value = "")
  public ErrorCodeEnum getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(ErrorCodeEnum errorCode) {
    this.errorCode = errorCode;
  }

  public ChargingStationStatusDataDTO info(String info) {
    this.info = info;
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  @ApiModelProperty(value = "")
  public String getInfo() {
    return info;
  }

  public void setInfo(String info) {
    this.info = info;
  }

  public ChargingStationStatusDataDTO lastStatusNotificationTimestamp(OffsetDateTime lastStatusNotificationTimestamp) {
    this.lastStatusNotificationTimestamp = lastStatusNotificationTimestamp;
    return this;
  }

   /**
   * Get lastStatusNotificationTimestamp
   * @return lastStatusNotificationTimestamp
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastStatusNotificationTimestamp() {
    return lastStatusNotificationTimestamp;
  }

  public void setLastStatusNotificationTimestamp(OffsetDateTime lastStatusNotificationTimestamp) {
    this.lastStatusNotificationTimestamp = lastStatusNotificationTimestamp;
  }

  public ChargingStationStatusDataDTO lastStatusNotificationReceived(OffsetDateTime lastStatusNotificationReceived) {
    this.lastStatusNotificationReceived = lastStatusNotificationReceived;
    return this;
  }

   /**
   * Get lastStatusNotificationReceived
   * @return lastStatusNotificationReceived
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastStatusNotificationReceived() {
    return lastStatusNotificationReceived;
  }

  public void setLastStatusNotificationReceived(OffsetDateTime lastStatusNotificationReceived) {
    this.lastStatusNotificationReceived = lastStatusNotificationReceived;
  }

  public ChargingStationStatusDataDTO statusVendorId(String statusVendorId) {
    this.statusVendorId = statusVendorId;
    return this;
  }

   /**
   * Get statusVendorId
   * @return statusVendorId
  **/
  @ApiModelProperty(value = "")
  public String getStatusVendorId() {
    return statusVendorId;
  }

  public void setStatusVendorId(String statusVendorId) {
    this.statusVendorId = statusVendorId;
  }

  public ChargingStationStatusDataDTO vendorErrorCode(String vendorErrorCode) {
    this.vendorErrorCode = vendorErrorCode;
    return this;
  }

   /**
   * Get vendorErrorCode
   * @return vendorErrorCode
  **/
  @ApiModelProperty(value = "")
  public String getVendorErrorCode() {
    return vendorErrorCode;
  }

  public void setVendorErrorCode(String vendorErrorCode) {
    this.vendorErrorCode = vendorErrorCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargingStationStatusDataDTO chargingStationStatusDataDTO = (ChargingStationStatusDataDTO) o;
    return Objects.equals(this.versionedData, chargingStationStatusDataDTO.versionedData) &&
        Objects.equals(this.status, chargingStationStatusDataDTO.status) &&
        Objects.equals(this.errorCode, chargingStationStatusDataDTO.errorCode) &&
        Objects.equals(this.info, chargingStationStatusDataDTO.info) &&
        Objects.equals(this.lastStatusNotificationTimestamp, chargingStationStatusDataDTO.lastStatusNotificationTimestamp) &&
        Objects.equals(this.lastStatusNotificationReceived, chargingStationStatusDataDTO.lastStatusNotificationReceived) &&
        Objects.equals(this.statusVendorId, chargingStationStatusDataDTO.statusVendorId) &&
        Objects.equals(this.vendorErrorCode, chargingStationStatusDataDTO.vendorErrorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versionedData, status, errorCode, info, lastStatusNotificationTimestamp, lastStatusNotificationReceived, statusVendorId, vendorErrorCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargingStationStatusDataDTO {\n");
    
    sb.append("    versionedData: ").append(toIndentedString(versionedData)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    lastStatusNotificationTimestamp: ").append(toIndentedString(lastStatusNotificationTimestamp)).append("\n");
    sb.append("    lastStatusNotificationReceived: ").append(toIndentedString(lastStatusNotificationReceived)).append("\n");
    sb.append("    statusVendorId: ").append(toIndentedString(statusVendorId)).append("\n");
    sb.append("    vendorErrorCode: ").append(toIndentedString(vendorErrorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

