/*
 * Business Partner REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ContractSupplierDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T18:44:40.010+01:00")
public class ContractSupplierDTO {
  @SerializedName("supplierIds")
  private List<Long> supplierIds = null;

  public ContractSupplierDTO supplierIds(List<Long> supplierIds) {
    this.supplierIds = supplierIds;
    return this;
  }

  public ContractSupplierDTO addSupplierIdsItem(Long supplierIdsItem) {
    if (this.supplierIds == null) {
      this.supplierIds = new ArrayList<Long>();
    }
    this.supplierIds.add(supplierIdsItem);
    return this;
  }

   /**
   * Get supplierIds
   * @return supplierIds
  **/
  @ApiModelProperty(value = "")
  public List<Long> getSupplierIds() {
    return supplierIds;
  }

  public void setSupplierIds(List<Long> supplierIds) {
    this.supplierIds = supplierIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractSupplierDTO contractSupplierDTO = (ContractSupplierDTO) o;
    return Objects.equals(this.supplierIds, contractSupplierDTO.supplierIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplierIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractSupplierDTO {\n");
    
    sb.append("    supplierIds: ").append(toIndentedString(supplierIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

