/*
 * Roaming REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Identification;
import java.io.IOException;

/**
 * ERoamingAuthorizeStop
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T18:37:18.317+01:00")
public class ERoamingAuthorizeStop {
  @SerializedName("Identification")
  private Identification identification = null;

  @SerializedName("OperatorID")
  private String operatorID = null;

  @SerializedName("CPOPartnerSessionID")
  private String cpOPartnerSessionID = null;

  @SerializedName("EMPPartnerSessionID")
  private String emPPartnerSessionID = null;

  @SerializedName("EvseID")
  private String evseID = null;

  @SerializedName("SessionID")
  private String sessionID = null;

  public ERoamingAuthorizeStop identification(Identification identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @ApiModelProperty(required = true, value = "")
  public Identification getIdentification() {
    return identification;
  }

  public void setIdentification(Identification identification) {
    this.identification = identification;
  }

  public ERoamingAuthorizeStop operatorID(String operatorID) {
    this.operatorID = operatorID;
    return this;
  }

   /**
   * Get operatorID
   * @return operatorID
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOperatorID() {
    return operatorID;
  }

  public void setOperatorID(String operatorID) {
    this.operatorID = operatorID;
  }

  public ERoamingAuthorizeStop cpOPartnerSessionID(String cpOPartnerSessionID) {
    this.cpOPartnerSessionID = cpOPartnerSessionID;
    return this;
  }

   /**
   * Get cpOPartnerSessionID
   * @return cpOPartnerSessionID
  **/
  @ApiModelProperty(value = "")
  public String getCpOPartnerSessionID() {
    return cpOPartnerSessionID;
  }

  public void setCpOPartnerSessionID(String cpOPartnerSessionID) {
    this.cpOPartnerSessionID = cpOPartnerSessionID;
  }

  public ERoamingAuthorizeStop emPPartnerSessionID(String emPPartnerSessionID) {
    this.emPPartnerSessionID = emPPartnerSessionID;
    return this;
  }

   /**
   * Get emPPartnerSessionID
   * @return emPPartnerSessionID
  **/
  @ApiModelProperty(value = "")
  public String getEmPPartnerSessionID() {
    return emPPartnerSessionID;
  }

  public void setEmPPartnerSessionID(String emPPartnerSessionID) {
    this.emPPartnerSessionID = emPPartnerSessionID;
  }

  public ERoamingAuthorizeStop evseID(String evseID) {
    this.evseID = evseID;
    return this;
  }

   /**
   * Get evseID
   * @return evseID
  **/
  @ApiModelProperty(value = "")
  public String getEvseID() {
    return evseID;
  }

  public void setEvseID(String evseID) {
    this.evseID = evseID;
  }

  public ERoamingAuthorizeStop sessionID(String sessionID) {
    this.sessionID = sessionID;
    return this;
  }

   /**
   * Get sessionID
   * @return sessionID
  **/
  @ApiModelProperty(value = "")
  public String getSessionID() {
    return sessionID;
  }

  public void setSessionID(String sessionID) {
    this.sessionID = sessionID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ERoamingAuthorizeStop eroamingAuthorizeStop = (ERoamingAuthorizeStop) o;
    return Objects.equals(this.identification, eroamingAuthorizeStop.identification) &&
        Objects.equals(this.operatorID, eroamingAuthorizeStop.operatorID) &&
        Objects.equals(this.cpOPartnerSessionID, eroamingAuthorizeStop.cpOPartnerSessionID) &&
        Objects.equals(this.emPPartnerSessionID, eroamingAuthorizeStop.emPPartnerSessionID) &&
        Objects.equals(this.evseID, eroamingAuthorizeStop.evseID) &&
        Objects.equals(this.sessionID, eroamingAuthorizeStop.sessionID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identification, operatorID, cpOPartnerSessionID, emPPartnerSessionID, evseID, sessionID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ERoamingAuthorizeStop {\n");
    
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    operatorID: ").append(toIndentedString(operatorID)).append("\n");
    sb.append("    cpOPartnerSessionID: ").append(toIndentedString(cpOPartnerSessionID)).append("\n");
    sb.append("    emPPartnerSessionID: ").append(toIndentedString(emPPartnerSessionID)).append("\n");
    sb.append("    evseID: ").append(toIndentedString(evseID)).append("\n");
    sb.append("    sessionID: ").append(toIndentedString(sessionID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

