/*
 * Business Partner REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FixedRoleCoreDTO;
import io.swagger.client.model.PermissionNodeCoreDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * FixedRoleInitDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T18:44:40.010+01:00")
public class FixedRoleInitDTO {
  @SerializedName("coreData")
  private FixedRoleCoreDTO coreData = null;

  @SerializedName("nodes")
  private List<PermissionNodeCoreDTO> nodes = null;

  public FixedRoleInitDTO coreData(FixedRoleCoreDTO coreData) {
    this.coreData = coreData;
    return this;
  }

   /**
   * Get coreData
   * @return coreData
  **/
  @ApiModelProperty(value = "")
  public FixedRoleCoreDTO getCoreData() {
    return coreData;
  }

  public void setCoreData(FixedRoleCoreDTO coreData) {
    this.coreData = coreData;
  }

  public FixedRoleInitDTO nodes(List<PermissionNodeCoreDTO> nodes) {
    this.nodes = nodes;
    return this;
  }

  public FixedRoleInitDTO addNodesItem(PermissionNodeCoreDTO nodesItem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<PermissionNodeCoreDTO>();
    }
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @ApiModelProperty(value = "")
  public List<PermissionNodeCoreDTO> getNodes() {
    return nodes;
  }

  public void setNodes(List<PermissionNodeCoreDTO> nodes) {
    this.nodes = nodes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FixedRoleInitDTO fixedRoleInitDTO = (FixedRoleInitDTO) o;
    return Objects.equals(this.coreData, fixedRoleInitDTO.coreData) &&
        Objects.equals(this.nodes, fixedRoleInitDTO.nodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coreData, nodes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FixedRoleInitDTO {\n");
    
    sb.append("    coreData: ").append(toIndentedString(coreData)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

