/*
 * CS Communicator REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AbstractResponseDTO;
import io.swagger.client.model.KeyValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetConfigurationResponseDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T19:06:01.588+01:00")
public class GetConfigurationResponseDTO extends AbstractResponseDTO {
  @SerializedName("configurationKey")
  private List<KeyValue> configurationKey = null;

  @SerializedName("unknownKey")
  private List<String> unknownKey = null;

  public GetConfigurationResponseDTO configurationKey(List<KeyValue> configurationKey) {
    this.configurationKey = configurationKey;
    return this;
  }

  public GetConfigurationResponseDTO addConfigurationKeyItem(KeyValue configurationKeyItem) {
    if (this.configurationKey == null) {
      this.configurationKey = new ArrayList<KeyValue>();
    }
    this.configurationKey.add(configurationKeyItem);
    return this;
  }

   /**
   * Get configurationKey
   * @return configurationKey
  **/
  @ApiModelProperty(value = "")
  public List<KeyValue> getConfigurationKey() {
    return configurationKey;
  }

  public void setConfigurationKey(List<KeyValue> configurationKey) {
    this.configurationKey = configurationKey;
  }

  public GetConfigurationResponseDTO unknownKey(List<String> unknownKey) {
    this.unknownKey = unknownKey;
    return this;
  }

  public GetConfigurationResponseDTO addUnknownKeyItem(String unknownKeyItem) {
    if (this.unknownKey == null) {
      this.unknownKey = new ArrayList<String>();
    }
    this.unknownKey.add(unknownKeyItem);
    return this;
  }

   /**
   * Get unknownKey
   * @return unknownKey
  **/
  @ApiModelProperty(value = "")
  public List<String> getUnknownKey() {
    return unknownKey;
  }

  public void setUnknownKey(List<String> unknownKey) {
    this.unknownKey = unknownKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetConfigurationResponseDTO getConfigurationResponseDTO = (GetConfigurationResponseDTO) o;
    return Objects.equals(this.configurationKey, getConfigurationResponseDTO.configurationKey) &&
        Objects.equals(this.unknownKey, getConfigurationResponseDTO.unknownKey) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configurationKey, unknownKey, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetConfigurationResponseDTO {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    configurationKey: ").append(toIndentedString(configurationKey)).append("\n");
    sb.append("    unknownKey: ").append(toIndentedString(unknownKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

