/*
 * Business Partner REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.VersionedData;
import java.io.IOException;

/**
 * MediaListDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T18:44:40.010+01:00")
public class MediaListDTO {
  @SerializedName("versionedData")
  private VersionedData versionedData = null;

  @SerializedName("idTag")
  private String idTag = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("cardNumber")
  private String cardNumber = null;

  @SerializedName("customerNumber")
  private String customerNumber = null;

  @SerializedName("blocked")
  private Boolean blocked = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("directOcc")
  private Boolean directOcc = null;

  @SerializedName("hubject")
  private Boolean hubject = null;

  @SerializedName("empId")
  private Long empId = null;

  public MediaListDTO versionedData(VersionedData versionedData) {
    this.versionedData = versionedData;
    return this;
  }

   /**
   * Get versionedData
   * @return versionedData
  **/
  @ApiModelProperty(value = "")
  public VersionedData getVersionedData() {
    return versionedData;
  }

  public void setVersionedData(VersionedData versionedData) {
    this.versionedData = versionedData;
  }

  public MediaListDTO idTag(String idTag) {
    this.idTag = idTag;
    return this;
  }

   /**
   * Get idTag
   * @return idTag
  **/
  @ApiModelProperty(value = "")
  public String getIdTag() {
    return idTag;
  }

  public void setIdTag(String idTag) {
    this.idTag = idTag;
  }

  public MediaListDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MediaListDTO cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Get cardNumber
   * @return cardNumber
  **/
  @ApiModelProperty(value = "")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public MediaListDTO customerNumber(String customerNumber) {
    this.customerNumber = customerNumber;
    return this;
  }

   /**
   * Get customerNumber
   * @return customerNumber
  **/
  @ApiModelProperty(value = "")
  public String getCustomerNumber() {
    return customerNumber;
  }

  public void setCustomerNumber(String customerNumber) {
    this.customerNumber = customerNumber;
  }

  public MediaListDTO blocked(Boolean blocked) {
    this.blocked = blocked;
    return this;
  }

   /**
   * Get blocked
   * @return blocked
  **/
  @ApiModelProperty(value = "")
  public Boolean isBlocked() {
    return blocked;
  }

  public void setBlocked(Boolean blocked) {
    this.blocked = blocked;
  }

  public MediaListDTO active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public MediaListDTO directOcc(Boolean directOcc) {
    this.directOcc = directOcc;
    return this;
  }

   /**
   * Get directOcc
   * @return directOcc
  **/
  @ApiModelProperty(value = "")
  public Boolean isDirectOcc() {
    return directOcc;
  }

  public void setDirectOcc(Boolean directOcc) {
    this.directOcc = directOcc;
  }

  public MediaListDTO hubject(Boolean hubject) {
    this.hubject = hubject;
    return this;
  }

   /**
   * Get hubject
   * @return hubject
  **/
  @ApiModelProperty(value = "")
  public Boolean isHubject() {
    return hubject;
  }

  public void setHubject(Boolean hubject) {
    this.hubject = hubject;
  }

  public MediaListDTO empId(Long empId) {
    this.empId = empId;
    return this;
  }

   /**
   * Get empId
   * @return empId
  **/
  @ApiModelProperty(value = "")
  public Long getEmpId() {
    return empId;
  }

  public void setEmpId(Long empId) {
    this.empId = empId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediaListDTO mediaListDTO = (MediaListDTO) o;
    return Objects.equals(this.versionedData, mediaListDTO.versionedData) &&
        Objects.equals(this.idTag, mediaListDTO.idTag) &&
        Objects.equals(this.description, mediaListDTO.description) &&
        Objects.equals(this.cardNumber, mediaListDTO.cardNumber) &&
        Objects.equals(this.customerNumber, mediaListDTO.customerNumber) &&
        Objects.equals(this.blocked, mediaListDTO.blocked) &&
        Objects.equals(this.active, mediaListDTO.active) &&
        Objects.equals(this.directOcc, mediaListDTO.directOcc) &&
        Objects.equals(this.hubject, mediaListDTO.hubject) &&
        Objects.equals(this.empId, mediaListDTO.empId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versionedData, idTag, description, cardNumber, customerNumber, blocked, active, directOcc, hubject, empId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediaListDTO {\n");
    
    sb.append("    versionedData: ").append(toIndentedString(versionedData)).append("\n");
    sb.append("    idTag: ").append(toIndentedString(idTag)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    customerNumber: ").append(toIndentedString(customerNumber)).append("\n");
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    directOcc: ").append(toIndentedString(directOcc)).append("\n");
    sb.append("    hubject: ").append(toIndentedString(hubject)).append("\n");
    sb.append("    empId: ").append(toIndentedString(empId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

