/*
 * Roaming REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.HashedPIN;
import java.io.IOException;

/**
 * QRCodeIdentification
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T18:37:18.317+01:00")
public class QRCodeIdentification {
  @SerializedName("EvcoID")
  private String evcoID = null;

  @SerializedName("HashedPIN")
  private HashedPIN hashedPIN = null;

  @SerializedName("PIN")
  private String PIN = null;

  public QRCodeIdentification evcoID(String evcoID) {
    this.evcoID = evcoID;
    return this;
  }

   /**
   * Get evcoID
   * @return evcoID
  **/
  @ApiModelProperty(required = true, value = "")
  public String getEvcoID() {
    return evcoID;
  }

  public void setEvcoID(String evcoID) {
    this.evcoID = evcoID;
  }

  public QRCodeIdentification hashedPIN(HashedPIN hashedPIN) {
    this.hashedPIN = hashedPIN;
    return this;
  }

   /**
   * Get hashedPIN
   * @return hashedPIN
  **/
  @ApiModelProperty(value = "")
  public HashedPIN getHashedPIN() {
    return hashedPIN;
  }

  public void setHashedPIN(HashedPIN hashedPIN) {
    this.hashedPIN = hashedPIN;
  }

  public QRCodeIdentification PIN(String PIN) {
    this.PIN = PIN;
    return this;
  }

   /**
   * Get PIN
   * @return PIN
  **/
  @ApiModelProperty(value = "")
  public String getPIN() {
    return PIN;
  }

  public void setPIN(String PIN) {
    this.PIN = PIN;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QRCodeIdentification qrCodeIdentification = (QRCodeIdentification) o;
    return Objects.equals(this.evcoID, qrCodeIdentification.evcoID) &&
        Objects.equals(this.hashedPIN, qrCodeIdentification.hashedPIN) &&
        Objects.equals(this.PIN, qrCodeIdentification.PIN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(evcoID, hashedPIN, PIN);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QRCodeIdentification {\n");
    
    sb.append("    evcoID: ").append(toIndentedString(evcoID)).append("\n");
    sb.append("    hashedPIN: ").append(toIndentedString(hashedPIN)).append("\n");
    sb.append("    PIN: ").append(toIndentedString(PIN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

