/*
 * CS Management EMP REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RemoteChargingStationListDTO;
import io.swagger.client.model.RemoteEvseDataListDTO;
import io.swagger.client.model.VersionedData;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * RemoteEvseListDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T19:09:13.919+01:00")
public class RemoteEvseListDTO {
  @SerializedName("versionedData")
  private VersionedData versionedData = null;

  @SerializedName("chargingStationId")
  private Long chargingStationId = null;

  @SerializedName("evseId")
  private String evseId = null;

  @SerializedName("operatorId")
  private String operatorId = null;

  @SerializedName("operatorCountryCode")
  private String operatorCountryCode = null;

  @SerializedName("operatorCode")
  private String operatorCode = null;

  @SerializedName("externalChargingStationId")
  private String externalChargingStationId = null;

  @SerializedName("externalOperatorId")
  private String externalOperatorId = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    AVAILABLE("AVAILABLE"),
    
    PREPARING("PREPARING"),
    
    CHARGING("CHARGING"),
    
    SUSPENDED_EVSE("SUSPENDED_EVSE"),
    
    SUSPENDED_EV("SUSPENDED_EV"),
    
    FINISHING("FINISHING"),
    
    OCCUPIED("OCCUPIED"),
    
    RESERVED("RESERVED"),
    
    UNAVAILABLE("UNAVAILABLE"),
    
    UNKNOWN("UNKNOWN"),
    
    OFFLINE("OFFLINE"),
    
    FAULTED("FAULTED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("lastUpdate")
  private OffsetDateTime lastUpdate = null;

  @SerializedName("empId")
  private Long empId = null;

  @SerializedName("bpRoamingContractId")
  private Long bpRoamingContractId = null;

  @SerializedName("evseData")
  private RemoteEvseDataListDTO evseData = null;

  @SerializedName("createdOn")
  private OffsetDateTime createdOn = null;

  @SerializedName("chargingStation")
  private RemoteChargingStationListDTO chargingStation = null;

  public RemoteEvseListDTO versionedData(VersionedData versionedData) {
    this.versionedData = versionedData;
    return this;
  }

   /**
   * Get versionedData
   * @return versionedData
  **/
  @ApiModelProperty(value = "")
  public VersionedData getVersionedData() {
    return versionedData;
  }

  public void setVersionedData(VersionedData versionedData) {
    this.versionedData = versionedData;
  }

  public RemoteEvseListDTO chargingStationId(Long chargingStationId) {
    this.chargingStationId = chargingStationId;
    return this;
  }

   /**
   * Get chargingStationId
   * @return chargingStationId
  **/
  @ApiModelProperty(value = "")
  public Long getChargingStationId() {
    return chargingStationId;
  }

  public void setChargingStationId(Long chargingStationId) {
    this.chargingStationId = chargingStationId;
  }

  public RemoteEvseListDTO evseId(String evseId) {
    this.evseId = evseId;
    return this;
  }

   /**
   * Get evseId
   * @return evseId
  **/
  @ApiModelProperty(value = "")
  public String getEvseId() {
    return evseId;
  }

  public void setEvseId(String evseId) {
    this.evseId = evseId;
  }

  public RemoteEvseListDTO operatorId(String operatorId) {
    this.operatorId = operatorId;
    return this;
  }

   /**
   * Get operatorId
   * @return operatorId
  **/
  @ApiModelProperty(value = "")
  public String getOperatorId() {
    return operatorId;
  }

  public void setOperatorId(String operatorId) {
    this.operatorId = operatorId;
  }

  public RemoteEvseListDTO operatorCountryCode(String operatorCountryCode) {
    this.operatorCountryCode = operatorCountryCode;
    return this;
  }

   /**
   * Get operatorCountryCode
   * @return operatorCountryCode
  **/
  @ApiModelProperty(value = "")
  public String getOperatorCountryCode() {
    return operatorCountryCode;
  }

  public void setOperatorCountryCode(String operatorCountryCode) {
    this.operatorCountryCode = operatorCountryCode;
  }

  public RemoteEvseListDTO operatorCode(String operatorCode) {
    this.operatorCode = operatorCode;
    return this;
  }

   /**
   * Get operatorCode
   * @return operatorCode
  **/
  @ApiModelProperty(value = "")
  public String getOperatorCode() {
    return operatorCode;
  }

  public void setOperatorCode(String operatorCode) {
    this.operatorCode = operatorCode;
  }

  public RemoteEvseListDTO externalChargingStationId(String externalChargingStationId) {
    this.externalChargingStationId = externalChargingStationId;
    return this;
  }

   /**
   * Get externalChargingStationId
   * @return externalChargingStationId
  **/
  @ApiModelProperty(value = "")
  public String getExternalChargingStationId() {
    return externalChargingStationId;
  }

  public void setExternalChargingStationId(String externalChargingStationId) {
    this.externalChargingStationId = externalChargingStationId;
  }

  public RemoteEvseListDTO externalOperatorId(String externalOperatorId) {
    this.externalOperatorId = externalOperatorId;
    return this;
  }

   /**
   * Get externalOperatorId
   * @return externalOperatorId
  **/
  @ApiModelProperty(value = "")
  public String getExternalOperatorId() {
    return externalOperatorId;
  }

  public void setExternalOperatorId(String externalOperatorId) {
    this.externalOperatorId = externalOperatorId;
  }

  public RemoteEvseListDTO status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public RemoteEvseListDTO lastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

   /**
   * Get lastUpdate
   * @return lastUpdate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public RemoteEvseListDTO empId(Long empId) {
    this.empId = empId;
    return this;
  }

   /**
   * Get empId
   * @return empId
  **/
  @ApiModelProperty(value = "")
  public Long getEmpId() {
    return empId;
  }

  public void setEmpId(Long empId) {
    this.empId = empId;
  }

  public RemoteEvseListDTO bpRoamingContractId(Long bpRoamingContractId) {
    this.bpRoamingContractId = bpRoamingContractId;
    return this;
  }

   /**
   * Get bpRoamingContractId
   * @return bpRoamingContractId
  **/
  @ApiModelProperty(value = "")
  public Long getBpRoamingContractId() {
    return bpRoamingContractId;
  }

  public void setBpRoamingContractId(Long bpRoamingContractId) {
    this.bpRoamingContractId = bpRoamingContractId;
  }

  public RemoteEvseListDTO evseData(RemoteEvseDataListDTO evseData) {
    this.evseData = evseData;
    return this;
  }

   /**
   * Get evseData
   * @return evseData
  **/
  @ApiModelProperty(value = "")
  public RemoteEvseDataListDTO getEvseData() {
    return evseData;
  }

  public void setEvseData(RemoteEvseDataListDTO evseData) {
    this.evseData = evseData;
  }

  public RemoteEvseListDTO createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public RemoteEvseListDTO chargingStation(RemoteChargingStationListDTO chargingStation) {
    this.chargingStation = chargingStation;
    return this;
  }

   /**
   * Get chargingStation
   * @return chargingStation
  **/
  @ApiModelProperty(value = "")
  public RemoteChargingStationListDTO getChargingStation() {
    return chargingStation;
  }

  public void setChargingStation(RemoteChargingStationListDTO chargingStation) {
    this.chargingStation = chargingStation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteEvseListDTO remoteEvseListDTO = (RemoteEvseListDTO) o;
    return Objects.equals(this.versionedData, remoteEvseListDTO.versionedData) &&
        Objects.equals(this.chargingStationId, remoteEvseListDTO.chargingStationId) &&
        Objects.equals(this.evseId, remoteEvseListDTO.evseId) &&
        Objects.equals(this.operatorId, remoteEvseListDTO.operatorId) &&
        Objects.equals(this.operatorCountryCode, remoteEvseListDTO.operatorCountryCode) &&
        Objects.equals(this.operatorCode, remoteEvseListDTO.operatorCode) &&
        Objects.equals(this.externalChargingStationId, remoteEvseListDTO.externalChargingStationId) &&
        Objects.equals(this.externalOperatorId, remoteEvseListDTO.externalOperatorId) &&
        Objects.equals(this.status, remoteEvseListDTO.status) &&
        Objects.equals(this.lastUpdate, remoteEvseListDTO.lastUpdate) &&
        Objects.equals(this.empId, remoteEvseListDTO.empId) &&
        Objects.equals(this.bpRoamingContractId, remoteEvseListDTO.bpRoamingContractId) &&
        Objects.equals(this.evseData, remoteEvseListDTO.evseData) &&
        Objects.equals(this.createdOn, remoteEvseListDTO.createdOn) &&
        Objects.equals(this.chargingStation, remoteEvseListDTO.chargingStation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versionedData, chargingStationId, evseId, operatorId, operatorCountryCode, operatorCode, externalChargingStationId, externalOperatorId, status, lastUpdate, empId, bpRoamingContractId, evseData, createdOn, chargingStation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteEvseListDTO {\n");
    
    sb.append("    versionedData: ").append(toIndentedString(versionedData)).append("\n");
    sb.append("    chargingStationId: ").append(toIndentedString(chargingStationId)).append("\n");
    sb.append("    evseId: ").append(toIndentedString(evseId)).append("\n");
    sb.append("    operatorId: ").append(toIndentedString(operatorId)).append("\n");
    sb.append("    operatorCountryCode: ").append(toIndentedString(operatorCountryCode)).append("\n");
    sb.append("    operatorCode: ").append(toIndentedString(operatorCode)).append("\n");
    sb.append("    externalChargingStationId: ").append(toIndentedString(externalChargingStationId)).append("\n");
    sb.append("    externalOperatorId: ").append(toIndentedString(externalOperatorId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    empId: ").append(toIndentedString(empId)).append("\n");
    sb.append("    bpRoamingContractId: ").append(toIndentedString(bpRoamingContractId)).append("\n");
    sb.append("    evseData: ").append(toIndentedString(evseData)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    chargingStation: ").append(toIndentedString(chargingStation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

