/*
 * CS Management EMP REST API
 * ## Authentication options  ### OAuth2 / OpenID Connect  The supported authentication method is OpenID Connect via Keycloak. For testing APIs via Swaggerhub or Swagger UI, please use **client_id** `swagger`.  When developing applications against this API, a separate client application must be registered in Keycloak.  ### X-Token header authentication  Internal use only, deprecated. The core services use these authentication headers for system account based requests.  
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AddressDTO;
import io.swagger.client.model.ChargingInfoListDTO;
import io.swagger.client.model.LocationDTO;
import io.swagger.client.model.RoamingInfoDTO;
import io.swagger.client.model.TransactionInfoDTO;
import io.swagger.client.model.VersionedData;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * RemoteChargingTransactionListDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-12T19:09:13.919+01:00")
public class RemoteChargingTransactionListDTO {
  @SerializedName("versionedData")
  private VersionedData versionedData = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("PENDING"),
    
    OPEN("OPEN"),
    
    FINISHED("FINISHED"),
    
    FAILURE("FAILURE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("evseId")
  private String evseId = null;

  @SerializedName("empId")
  private Long empId = null;

  @SerializedName("externalChargingStationId")
  private String externalChargingStationId = null;

  @SerializedName("idTag")
  private String idTag = null;

  @SerializedName("cardNumber")
  private String cardNumber = null;

  @SerializedName("customerNumber")
  private String customerNumber = null;

  @SerializedName("transactionInfo")
  private TransactionInfoDTO transactionInfo = null;

  @SerializedName("chargingInfo")
  private ChargingInfoListDTO chargingInfo = null;

  @SerializedName("empSessionId")
  private String empSessionId = null;

  @SerializedName("csoSessionId")
  private String csoSessionId = null;

  @SerializedName("externalSessionId")
  private String externalSessionId = null;

  /**
   * Gets or Sets authorizationStatus
   */
  @JsonAdapter(AuthorizationStatusEnum.Adapter.class)
  public enum AuthorizationStatusEnum {
    ACCEPTED("ACCEPTED"),
    
    BLOCKED("BLOCKED"),
    
    EXPIRED("EXPIRED"),
    
    INVALID("INVALID"),
    
    CONCURRENT_TX("CONCURRENT_TX");

    private String value;

    AuthorizationStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AuthorizationStatusEnum fromValue(String text) {
      for (AuthorizationStatusEnum b : AuthorizationStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AuthorizationStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AuthorizationStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AuthorizationStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AuthorizationStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("authorizationStatus")
  private AuthorizationStatusEnum authorizationStatus = null;

  @SerializedName("roamingInfo")
  private RoamingInfoDTO roamingInfo = null;

  /**
   * Gets or Sets plausibility
   */
  @JsonAdapter(PlausibilityEnum.Adapter.class)
  public enum PlausibilityEnum {
    PLAUSIBLE("PLAUSIBLE"),
    
    NOT_PLAUSIBLE("NOT_PLAUSIBLE");

    private String value;

    PlausibilityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PlausibilityEnum fromValue(String text) {
      for (PlausibilityEnum b : PlausibilityEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PlausibilityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PlausibilityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PlausibilityEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PlausibilityEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("plausibility")
  private PlausibilityEnum plausibility = null;

  @SerializedName("createdOn")
  private OffsetDateTime createdOn = null;

  @SerializedName("duration")
  private Long duration = null;

  @SerializedName("transactionDuration")
  private Long transactionDuration = null;

  @SerializedName("address")
  private AddressDTO address = null;

  @SerializedName("stationLocation")
  private LocationDTO stationLocation = null;

  public RemoteChargingTransactionListDTO versionedData(VersionedData versionedData) {
    this.versionedData = versionedData;
    return this;
  }

   /**
   * Get versionedData
   * @return versionedData
  **/
  @ApiModelProperty(value = "")
  public VersionedData getVersionedData() {
    return versionedData;
  }

  public void setVersionedData(VersionedData versionedData) {
    this.versionedData = versionedData;
  }

  public RemoteChargingTransactionListDTO status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public RemoteChargingTransactionListDTO evseId(String evseId) {
    this.evseId = evseId;
    return this;
  }

   /**
   * Get evseId
   * @return evseId
  **/
  @ApiModelProperty(value = "")
  public String getEvseId() {
    return evseId;
  }

  public void setEvseId(String evseId) {
    this.evseId = evseId;
  }

  public RemoteChargingTransactionListDTO empId(Long empId) {
    this.empId = empId;
    return this;
  }

   /**
   * Get empId
   * @return empId
  **/
  @ApiModelProperty(value = "")
  public Long getEmpId() {
    return empId;
  }

  public void setEmpId(Long empId) {
    this.empId = empId;
  }

  public RemoteChargingTransactionListDTO externalChargingStationId(String externalChargingStationId) {
    this.externalChargingStationId = externalChargingStationId;
    return this;
  }

   /**
   * Get externalChargingStationId
   * @return externalChargingStationId
  **/
  @ApiModelProperty(value = "")
  public String getExternalChargingStationId() {
    return externalChargingStationId;
  }

  public void setExternalChargingStationId(String externalChargingStationId) {
    this.externalChargingStationId = externalChargingStationId;
  }

  public RemoteChargingTransactionListDTO idTag(String idTag) {
    this.idTag = idTag;
    return this;
  }

   /**
   * Get idTag
   * @return idTag
  **/
  @ApiModelProperty(value = "")
  public String getIdTag() {
    return idTag;
  }

  public void setIdTag(String idTag) {
    this.idTag = idTag;
  }

  public RemoteChargingTransactionListDTO cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Get cardNumber
   * @return cardNumber
  **/
  @ApiModelProperty(value = "")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public RemoteChargingTransactionListDTO customerNumber(String customerNumber) {
    this.customerNumber = customerNumber;
    return this;
  }

   /**
   * Get customerNumber
   * @return customerNumber
  **/
  @ApiModelProperty(value = "")
  public String getCustomerNumber() {
    return customerNumber;
  }

  public void setCustomerNumber(String customerNumber) {
    this.customerNumber = customerNumber;
  }

  public RemoteChargingTransactionListDTO transactionInfo(TransactionInfoDTO transactionInfo) {
    this.transactionInfo = transactionInfo;
    return this;
  }

   /**
   * Get transactionInfo
   * @return transactionInfo
  **/
  @ApiModelProperty(value = "")
  public TransactionInfoDTO getTransactionInfo() {
    return transactionInfo;
  }

  public void setTransactionInfo(TransactionInfoDTO transactionInfo) {
    this.transactionInfo = transactionInfo;
  }

  public RemoteChargingTransactionListDTO chargingInfo(ChargingInfoListDTO chargingInfo) {
    this.chargingInfo = chargingInfo;
    return this;
  }

   /**
   * Get chargingInfo
   * @return chargingInfo
  **/
  @ApiModelProperty(value = "")
  public ChargingInfoListDTO getChargingInfo() {
    return chargingInfo;
  }

  public void setChargingInfo(ChargingInfoListDTO chargingInfo) {
    this.chargingInfo = chargingInfo;
  }

  public RemoteChargingTransactionListDTO empSessionId(String empSessionId) {
    this.empSessionId = empSessionId;
    return this;
  }

   /**
   * Get empSessionId
   * @return empSessionId
  **/
  @ApiModelProperty(value = "")
  public String getEmpSessionId() {
    return empSessionId;
  }

  public void setEmpSessionId(String empSessionId) {
    this.empSessionId = empSessionId;
  }

  public RemoteChargingTransactionListDTO csoSessionId(String csoSessionId) {
    this.csoSessionId = csoSessionId;
    return this;
  }

   /**
   * Get csoSessionId
   * @return csoSessionId
  **/
  @ApiModelProperty(value = "")
  public String getCsoSessionId() {
    return csoSessionId;
  }

  public void setCsoSessionId(String csoSessionId) {
    this.csoSessionId = csoSessionId;
  }

  public RemoteChargingTransactionListDTO externalSessionId(String externalSessionId) {
    this.externalSessionId = externalSessionId;
    return this;
  }

   /**
   * Get externalSessionId
   * @return externalSessionId
  **/
  @ApiModelProperty(value = "")
  public String getExternalSessionId() {
    return externalSessionId;
  }

  public void setExternalSessionId(String externalSessionId) {
    this.externalSessionId = externalSessionId;
  }

  public RemoteChargingTransactionListDTO authorizationStatus(AuthorizationStatusEnum authorizationStatus) {
    this.authorizationStatus = authorizationStatus;
    return this;
  }

   /**
   * Get authorizationStatus
   * @return authorizationStatus
  **/
  @ApiModelProperty(value = "")
  public AuthorizationStatusEnum getAuthorizationStatus() {
    return authorizationStatus;
  }

  public void setAuthorizationStatus(AuthorizationStatusEnum authorizationStatus) {
    this.authorizationStatus = authorizationStatus;
  }

  public RemoteChargingTransactionListDTO roamingInfo(RoamingInfoDTO roamingInfo) {
    this.roamingInfo = roamingInfo;
    return this;
  }

   /**
   * Get roamingInfo
   * @return roamingInfo
  **/
  @ApiModelProperty(value = "")
  public RoamingInfoDTO getRoamingInfo() {
    return roamingInfo;
  }

  public void setRoamingInfo(RoamingInfoDTO roamingInfo) {
    this.roamingInfo = roamingInfo;
  }

  public RemoteChargingTransactionListDTO plausibility(PlausibilityEnum plausibility) {
    this.plausibility = plausibility;
    return this;
  }

   /**
   * Get plausibility
   * @return plausibility
  **/
  @ApiModelProperty(value = "")
  public PlausibilityEnum getPlausibility() {
    return plausibility;
  }

  public void setPlausibility(PlausibilityEnum plausibility) {
    this.plausibility = plausibility;
  }

  public RemoteChargingTransactionListDTO createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public RemoteChargingTransactionListDTO duration(Long duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration in milliseconds
   * @return duration
  **/
  @ApiModelProperty(value = "Duration in milliseconds")
  public Long getDuration() {
    return duration;
  }

  public void setDuration(Long duration) {
    this.duration = duration;
  }

  public RemoteChargingTransactionListDTO transactionDuration(Long transactionDuration) {
    this.transactionDuration = transactionDuration;
    return this;
  }

   /**
   * TransactionDuration in milliseconds
   * @return transactionDuration
  **/
  @ApiModelProperty(value = "TransactionDuration in milliseconds")
  public Long getTransactionDuration() {
    return transactionDuration;
  }

  public void setTransactionDuration(Long transactionDuration) {
    this.transactionDuration = transactionDuration;
  }

  public RemoteChargingTransactionListDTO address(AddressDTO address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public AddressDTO getAddress() {
    return address;
  }

  public void setAddress(AddressDTO address) {
    this.address = address;
  }

  public RemoteChargingTransactionListDTO stationLocation(LocationDTO stationLocation) {
    this.stationLocation = stationLocation;
    return this;
  }

   /**
   * Get stationLocation
   * @return stationLocation
  **/
  @ApiModelProperty(value = "")
  public LocationDTO getStationLocation() {
    return stationLocation;
  }

  public void setStationLocation(LocationDTO stationLocation) {
    this.stationLocation = stationLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteChargingTransactionListDTO remoteChargingTransactionListDTO = (RemoteChargingTransactionListDTO) o;
    return Objects.equals(this.versionedData, remoteChargingTransactionListDTO.versionedData) &&
        Objects.equals(this.status, remoteChargingTransactionListDTO.status) &&
        Objects.equals(this.evseId, remoteChargingTransactionListDTO.evseId) &&
        Objects.equals(this.empId, remoteChargingTransactionListDTO.empId) &&
        Objects.equals(this.externalChargingStationId, remoteChargingTransactionListDTO.externalChargingStationId) &&
        Objects.equals(this.idTag, remoteChargingTransactionListDTO.idTag) &&
        Objects.equals(this.cardNumber, remoteChargingTransactionListDTO.cardNumber) &&
        Objects.equals(this.customerNumber, remoteChargingTransactionListDTO.customerNumber) &&
        Objects.equals(this.transactionInfo, remoteChargingTransactionListDTO.transactionInfo) &&
        Objects.equals(this.chargingInfo, remoteChargingTransactionListDTO.chargingInfo) &&
        Objects.equals(this.empSessionId, remoteChargingTransactionListDTO.empSessionId) &&
        Objects.equals(this.csoSessionId, remoteChargingTransactionListDTO.csoSessionId) &&
        Objects.equals(this.externalSessionId, remoteChargingTransactionListDTO.externalSessionId) &&
        Objects.equals(this.authorizationStatus, remoteChargingTransactionListDTO.authorizationStatus) &&
        Objects.equals(this.roamingInfo, remoteChargingTransactionListDTO.roamingInfo) &&
        Objects.equals(this.plausibility, remoteChargingTransactionListDTO.plausibility) &&
        Objects.equals(this.createdOn, remoteChargingTransactionListDTO.createdOn) &&
        Objects.equals(this.duration, remoteChargingTransactionListDTO.duration) &&
        Objects.equals(this.transactionDuration, remoteChargingTransactionListDTO.transactionDuration) &&
        Objects.equals(this.address, remoteChargingTransactionListDTO.address) &&
        Objects.equals(this.stationLocation, remoteChargingTransactionListDTO.stationLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versionedData, status, evseId, empId, externalChargingStationId, idTag, cardNumber, customerNumber, transactionInfo, chargingInfo, empSessionId, csoSessionId, externalSessionId, authorizationStatus, roamingInfo, plausibility, createdOn, duration, transactionDuration, address, stationLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteChargingTransactionListDTO {\n");
    
    sb.append("    versionedData: ").append(toIndentedString(versionedData)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    evseId: ").append(toIndentedString(evseId)).append("\n");
    sb.append("    empId: ").append(toIndentedString(empId)).append("\n");
    sb.append("    externalChargingStationId: ").append(toIndentedString(externalChargingStationId)).append("\n");
    sb.append("    idTag: ").append(toIndentedString(idTag)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    customerNumber: ").append(toIndentedString(customerNumber)).append("\n");
    sb.append("    transactionInfo: ").append(toIndentedString(transactionInfo)).append("\n");
    sb.append("    chargingInfo: ").append(toIndentedString(chargingInfo)).append("\n");
    sb.append("    empSessionId: ").append(toIndentedString(empSessionId)).append("\n");
    sb.append("    csoSessionId: ").append(toIndentedString(csoSessionId)).append("\n");
    sb.append("    externalSessionId: ").append(toIndentedString(externalSessionId)).append("\n");
    sb.append("    authorizationStatus: ").append(toIndentedString(authorizationStatus)).append("\n");
    sb.append("    roamingInfo: ").append(toIndentedString(roamingInfo)).append("\n");
    sb.append("    plausibility: ").append(toIndentedString(plausibility)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    transactionDuration: ").append(toIndentedString(transactionDuration)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    stationLocation: ").append(toIndentedString(stationLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

